version: '3.8'

services:
  web:
    build: .
    image: jjp006/ocr1:${IMAGE_TAG}
    container_name: ocr_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      - FLASK_ENV=ocr_blog.flaskenv
      - FLASK_APP=ocr_blog.py
