name: Deploy to EC2

on:
  push:
    branches:
      - main   # or any branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.172.31.88.232 }}  # Private IPv4 address

    - name: Copy project files to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ec2-user@23.20.6.222:~/OCR1_project/  # Public IPv4 address

    - name: Deploy using Docker Compose on EC2
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@23.20.6.222 << EOF  # Public IPv4 address
          cd ~/OCR1_project
          IMAGE_TAG=$IMAGE_TAG docker-compose pull
          IMAGE_TAG=$IMAGE_TAG docker-compose up -d
        EOF
        