name: Deploy to EC2

on:
  push:
    branches:
      - main   # or any branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        # Create the key file with proper formatting
        cat << 'EOF' > ~/.ssh/ec2_key.pem
        ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        EOF
        # Remove any potential BOM or extra characters
        sed -i '1s/^\xEF\xBB\xBF//' ~/.ssh/ec2_key.pem
        # Ensure proper line endings
        dos2unix ~/.ssh/ec2_key.pem
        # Set proper permissions
        chmod 600 ~/.ssh/ec2_key.pem
        # Verify key format and show fingerprint
        ssh-keygen -l -f ~/.ssh/ec2_key.pem || echo "Key format verification failed"
        # Start SSH agent
        eval $(ssh-agent -s)
        # Add key to agent
        ssh-add ~/.ssh/ec2_key.pem
        # List added keys
        ssh-add -l
        # Debug: Show first few lines of key (safely)
        head -n 1 ~/.ssh/ec2_key.pem
        tail -n 1 ~/.ssh/ec2_key.pem

    - name: Install dos2unix
      run: sudo apt-get install -y dos2unix

    - name: Add SSH key to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP_HOST }} >> ~/.ssh/known_hosts

    - name: Debug SSH connection
      run: |
        # Test SSH connection with explicit key
        ssh -i ~/.ssh/ec2_key.pem -v -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP_HOST }} 'echo "SSH connection successful"'

    - name: Copy project files to EC2
      run: |
        rsync -avz -e "ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no" ./ ec2-user@${{ secrets.EC2_PUBLIC_IP_HOST }}:~/OCR1_project/

    - name: Deploy using Docker Compose on EC2
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP_HOST }} << EOF
          cd ~/OCR1_project
          IMAGE_TAG=$IMAGE_TAG docker-compose pull
          IMAGE_TAG=$IMAGE_TAG docker-compose up -d
        EOF
        