name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Copy Files to EC2"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy using Docker Compose on EC2
      env:
        IMAGE_TAG: ${{ github.sha }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
            "echo \"=== Starting Deployment ===\"",
            "cd ~/OCR1_project",
            
            "echo \"=== Checking docker-compose.yml ===\"",
            "cat docker-compose.yml",
            
            "echo \"=== Checking Docker Status ===\"",
            "docker info",
            "docker ps -a",
            
            "echo \"=== Logging into Docker Hub ===\"",
            "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin",
            
            "echo \"=== Pulling Latest Image ===\"",
            "docker pull jjp006/ocr1:${IMAGE_TAG} || exit 1",
            
            "echo \"=== Setting up Environment ===\"",
            "export IMAGE_TAG=${IMAGE_TAG}",
            "envsubst < docker-compose.yml > docker-compose.generated.yml",
            
            "echo \"=== Starting Containers ===\"",
            "docker-compose -f docker-compose.generated.yml up -d --build --force-recreate || exit 1",
            
            "echo \"=== Verifying Container Status ===\"",
            "sleep 5",
            "docker ps -a",
            "docker logs ocr_web",
            
            "echo \"=== Checking Container Health ===\"",
            "curl -v http://localhost:8000 || echo \"Container not responding yet\"",
            
            "echo \"=== Configuring Nginx ===\"",
            "echo \"server { listen 80; server_name _; location / { proxy_pass http://127.0.0.1:8000; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto \$scheme; } }\" | sudo tee /etc/nginx/sites-available/ocr1",
            "sudo ln -sf /etc/nginx/sites-available/ocr1 /etc/nginx/sites-enabled/",
            "sudo nginx -t && sudo systemctl restart nginx",
            
            "echo \"=== Final Health Check ===\"",
            "sleep 10",
            "curl -f http://localhost:8000 || echo \"Warning: Application not responding\"",
            "docker ps -a",
            "docker logs ocr_web"
          ]'

        