name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Copy Files to EC2"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy using Docker Compose on EC2
      env:
        IMAGE_TAG: ${{ github.sha }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
            "cd ~/OCR1_project",
            "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin",
            "docker pull jjp006/ocr1:${IMAGE_TAG}",
            "docker tag jjp006/ocr1:${IMAGE_TAG} jjp006/ocr1:latest",
            "export IMAGE_TAG=${IMAGE_TAG}",
            "envsubst < docker-compose.yml > docker-compose.generated.yml",
            "docker-compose -f docker-compose.generated.yml down --remove-orphans",
            "docker-compose -f docker-compose.generated.yml up -d --build --force-recreate",
            "docker ps -a",
            "docker logs ocr_web",
            "curl -f http://localhost:8000 || echo \"App not ready yet\"",
            "sudo systemctl restart nginx"
          ]'
        