name: test process to  EC2

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  create-files:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create files command to EC2
      run: |
        SHA=${{ github.sha }}
        REPO=${{ github.repository }}

        # Escape slashes in REPO for safe filename
        REPO_SAFE="${REPO//\//_}"

        aws ssm send-command \
        --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
        --document-name "AWS-RunShellScript" \
        --comment "Cloning repo on EC2" \
        --parameters "commands=[
            \"echo '=== Removing old OCR1_project directory ==='\",
            \"touch test-${SHA}-${REPO_SAFE}.txt\",
            \"echo '=== FINISHED ==='\",
            \"ls -la ~/\"
        ]"